### ISSUE TITLE
Use "3.7" for docker compose and replace legacy flags with modern ones

### ISSUE THREAD

**Issue by sjefvanleeuwen** [JasonBBelcher/insiten-code-challenge#34]
Warning: The --link flag is a legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link. One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.

Use:
   depends_on:
      - db
      - redis

instead./

**Comment by JasonBBelcher** [comment]
fixed.
